basePath: /trade-bot
definitions:
  balance.Balance:
    properties:
      discount:
        type: integer
      forward:
        type: integer
      original_balance:
        type: integer
      reverse:
        type: integer
      total:
        type: integer
      trade_count:
        type: integer
      trade_day:
        type: string
    type: object
  bidask.BidAskProto:
    properties:
      bid_ask:
        $ref: '#/definitions/bidask.BidAskProto_BidAskData'
      exchange:
        type: string
    type: object
  bidask.BidAskProto_BidAskData:
    properties:
      ask_price:
        items:
          type: number
        type: array
      ask_volume:
        items:
          type: integer
        type: array
      bid_price:
        items:
          type: number
        type: array
      bid_volume:
        items:
          type: integer
        type: array
      code:
        type: string
      date_time:
        type: string
      diff_ask_vol:
        items:
          type: integer
        type: array
      diff_bid_vol:
        items:
          type: integer
        type: array
      simtrade:
        type: integer
      suspend:
        type: integer
    type: object
  global.SystemSwitch:
    properties:
      buy:
        type: boolean
      buy_later:
        type: boolean
      mean_time_reverse_trade_stock_num:
        type: integer
      mean_time_trade_stock_num:
        type: integer
      sell:
        type: boolean
      sell_first:
        type: boolean
      use_bid_ask:
        type: boolean
    type: object
  handlers.ErrorResponse:
    properties:
      attachment: {}
      response:
        type: string
    type: object
  manualtradehandler.ManualBuyLaterBody:
    properties:
      price:
        type: number
      stock_num:
        type: string
    type: object
  manualtradehandler.ManualSellBody:
    properties:
      price:
        type: number
      stock_num:
        type: string
    type: object
  simulate.Result:
    properties:
      balance:
        type: integer
      cond:
        $ref: '#/definitions/simulationcond.AnalyzeCondition'
      cond_id:
        type: integer
      forward_balance:
        type: integer
      is_best_forward:
        type: boolean
      is_best_reverse:
        type: boolean
      positive_days:
        type: integer
      reverse_balance:
        type: integer
      total_days:
        type: integer
      total_loss:
        type: integer
      trade_count:
        type: integer
      trade_day:
        type: string
    type: object
  simulationcond.AnalyzeCondition:
    properties:
      close_change_ratio_high:
        type: number
      close_change_ratio_low:
        type: number
      forward_out_in_ratio:
        type: number
      history_close_count:
        type: integer
      open_change_ratio:
        type: number
      reverse_out_in_ratio:
        type: number
      rsi_high:
        type: number
      rsi_low:
        type: number
      ticks_period_count:
        type: integer
      ticks_period_limit:
        type: number
      ticks_period_threshold:
        type: number
      trim_history_close_count:
        type: boolean
      volume_per_second:
        type: integer
    type: object
  streamtick.StreamTickProto:
    properties:
      exchange:
        type: string
      tick:
        $ref: '#/definitions/streamtick.StreamTickProto_TickData'
    type: object
  streamtick.StreamTickProto_TickData:
    properties:
      amount:
        type: number
      ask_side_total_cnt:
        type: integer
      ask_side_total_vol:
        type: integer
      avg_price:
        type: number
      bid_side_total_cnt:
        type: integer
      bid_side_total_vol:
        type: integer
      chg_type:
        type: integer
      close:
        type: number
      code:
        type: string
      date_time:
        type: string
      high:
        type: number
      low:
        type: number
      open:
        type: number
      pct_chg:
        type: number
      price_chg:
        type: number
      simtrade:
        type: integer
      suspend:
        type: integer
      tick_type:
        type: integer
      total_amount:
        type: number
      total_volume:
        type: integer
      volume:
        type: integer
    type: object
  sysparm.Parameters:
    properties:
      key:
        type: string
      value:
        type: string
    type: object
  targethandler.TargetResponse:
    properties:
      close:
        type: number
      stock_num:
        type: string
    type: object
  tradeevent.EventProto:
    properties:
      event:
        type: string
      event_code:
        type: integer
      info:
        type: string
      resp_code:
        type: integer
    type: object
  traderecord.TradeRecordArrProto:
    properties:
      data:
        items:
          $ref: '#/definitions/traderecord.TradeRecordProto'
        type: array
    type: object
  traderecord.TradeRecordProto:
    properties:
      action:
        type: string
      code:
        type: string
      id:
        type: string
      order_time:
        type: string
      price:
        type: number
      quantity:
        type: integer
      status:
        type: string
    type: object
info:
  contact: {}
  description: API docs for ToC Trader
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: ToC Trader
  version: 1.4.0
paths:
  /balance:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: DeletaAllBalance
      tags:
      - Balance
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/balance.Balance'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: GetAllBalance
      tags:
      - Balance
    post:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: body
        required: true
        schema:
          items:
            $ref: '#/definitions/balance.Balance'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: ImportBalance
      tags:
      - Balance
  /condition:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: DeletaAllResultAndCond
      tags:
      - TradeCondition
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/simulate.Result'
            type: array
      summary: GetLatestTradeCondition
      tags:
      - TradeCondition
    post:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: body
        required: true
        schema:
          items:
            $ref: '#/definitions/simulate.Result'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: ImpoprtTradeCondition
      tags:
      - TradeCondition
  /condition/latest:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/simulationcond.AnalyzeCondition'
            type: array
      summary: GetLatestTradeCondition
      tags:
      - TradeCondition
  /data/bid-ask:
    post:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/bidask.BidAskProto'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: ReceiveBidAsk
      tags:
      - Data
  /data/streamtick:
    post:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/streamtick.StreamTickProto'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: ReceiveStreamTick
      tags:
      - Data
  /manual/buy-later:
    post:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/manualtradehandler.ManualBuyLaterBody'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: ManualBuyLaterStock
      tags:
      - ManualTrade
  /manual/sell:
    post:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/manualtradehandler.ManualSellBody'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: ManualSellStock
      tags:
      - ManualTrade
  /system/restart:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Restart
      tags:
      - MainSystem
  /system/sysparm:
    post:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: body
        required: true
        schema:
          items:
            $ref: '#/definitions/sysparm.Parameters'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: UpdateSysparm
      tags:
      - MainSystem
  /target:
    get:
      consumes:
      - application/json
      parameters:
      - description: count
        in: header
        name: count
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/targethandler.TargetResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: GetTarget
      tags:
      - Target
  /trade-event:
    post:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/tradeevent.EventProto'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: ReciveTradeEvent
      tags:
      - TradeEvent
  /trade-record:
    post:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/traderecord.TradeRecordArrProto'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: UpdateTradeRecord
      tags:
      - TradeRecord
  /trade/switch:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/global.SystemSwitch'
      summary: GetTradeBotSwitch
      tags:
      - MainSystem
    put:
      consumes:
      - application/json
      parameters:
      - description: Body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/global.SystemSwitch'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: UpdateTradeBotSwitch
      tags:
      - MainSystem
swagger: "2.0"
